// Spanish Vocabulary Database - 500 Most Common Words
const vocabulary = [
    // Common Greetings & Phrases (1-20)
    { id: 1, spanish: "hola", english: "hello", example: "Hola, ¿cómo estás?", translation: "Hello, how are you?" },
    { id: 2, spanish: "adiós", english: "goodbye", example: "Adiós, hasta luego.", translation: "Goodbye, see you later." },
    { id: 3, spanish: "gracias", english: "thank you", example: "Gracias por tu ayuda.", translation: "Thank you for your help." },
    { id: 4, spanish: "por favor", english: "please", example: "Por favor, ayúdame.", translation: "Please, help me." },
    { id: 5, spanish: "sí", english: "yes", example: "Sí, estoy de acuerdo.", translation: "Yes, I agree." },
    { id: 6, spanish: "no", english: "no", example: "No, no quiero ir.", translation: "No, I don't want to go." },
    { id: 7, spanish: "perdón", english: "sorry/excuse me", example: "Perdón, no te escuché.", translation: "Sorry, I didn't hear you." },
    { id: 8, spanish: "disculpa", english: "excuse me", example: "Disculpa, ¿dónde está el baño?", translation: "Excuse me, where is the bathroom?" },
    { id: 9, spanish: "de nada", english: "you're welcome", example: "De nada, con mucho gusto.", translation: "You're welcome, with pleasure." },
    { id: 10, spanish: "buenos días", english: "good morning", example: "Buenos días, ¿cómo amaneció?", translation: "Good morning, how did you wake up?" },
    { id: 11, spanish: "buenas tardes", english: "good afternoon", example: "Buenas tardes, señor.", translation: "Good afternoon, sir." },
    { id: 12, spanish: "buenas noches", english: "good evening/night", example: "Buenas noches, hasta mañana.", translation: "Good night, see you tomorrow." },
    { id: 13, spanish: "hasta luego", english: "see you later", example: "Hasta luego, amigo.", translation: "See you later, friend." },
    { id: 14, spanish: "bienvenido", english: "welcome", example: "Bienvenido a mi casa.", translation: "Welcome to my house." },
    { id: 15, spanish: "felicidades", english: "congratulations", example: "Felicidades por tu graduación.", translation: "Congratulations on your graduation." },
    { id: 16, spanish: "salud", english: "cheers/bless you", example: "Salud, por la amistad.", translation: "Cheers, to friendship." },
    { id: 17, spanish: "claro", english: "of course/clear", example: "Claro, te puedo ayudar.", translation: "Of course, I can help you." },
    { id: 18, spanish: "tal vez", english: "maybe/perhaps", example: "Tal vez vaya mañana.", translation: "Maybe I'll go tomorrow." },
    { id: 19, spanish: "cuidado", english: "careful/be careful", example: "Cuidado con el escalón.", translation: "Be careful with the step." },
    { id: 20, spanish: "suerte", english: "luck/good luck", example: "Buena suerte en el examen.", translation: "Good luck on the exam." },

    // Essential Verbs - Present Tense (21-80)
    { id: 21, spanish: "ser", english: "to be (permanent)", example: "Soy de México.", translation: "I am from Mexico." },
    { id: 22, spanish: "estar", english: "to be (temporary)", example: "Estoy cansado hoy.", translation: "I am tired today." },
    { id: 23, spanish: "tener", english: "to have", example: "Tengo dos hermanos.", translation: "I have two brothers." },
    { id: 24, spanish: "hacer", english: "to do/make", example: "¿Qué vas a hacer hoy?", translation: "What are you going to do today?" },
    { id: 25, spanish: "ir", english: "to go", example: "Voy a ir al mercado.", translation: "I am going to go to the market." },
    { id: 26, spanish: "venir", english: "to come", example: "¿Puedes venir a mi casa?", translation: "Can you come to my house?" },
    { id: 27, spanish: "ver", english: "to see/watch", example: "Veo una película esta noche.", translation: "I'm watching a movie tonight." },
    { id: 28, spanish: "decir", english: "to say/tell", example: "¿Qué quieres decir?", translation: "What do you want to say?" },
    { id: 29, spanish: "saber", english: "to know (facts)", example: "Yo sé hablar español.", translation: "I know how to speak Spanish." },
    { id: 30, spanish: "conocer", english: "to know (people/places)", example: "Conozco un buen restaurante.", translation: "I know a good restaurant." },
    { id: 31, spanish: "querer", english: "to want", example: "Quiero aprender más español.", translation: "I want to learn more Spanish." },
    { id: 32, spanish: "poder", english: "to be able/can", example: "No puedo hacerlo solo.", translation: "I can't do it alone." },
    { id: 33, spanish: "dar", english: "to give", example: "Dame el libro, por favor.", translation: "Give me the book, please." },
    { id: 34, spanish: "poner", english: "to put/place", example: "Pon el libro en la mesa.", translation: "Put the book on the table." },
    { id: 35, spanish: "salir", english: "to leave/go out", example: "Salgo de casa a las ocho.", translation: "I leave home at eight." },
    { id: 36, spanish: "llegar", english: "to arrive", example: "Llego a las cinco.", translation: "I arrive at five." },
    { id: 37, spanish: "pasar", english: "to pass/happen", example: "¿Qué pasó ayer?", translation: "What happened yesterday?" },
    { id: 38, spanish: "quedar", english: "to stay/remain", example: "Me quedo en casa.", translation: "I'm staying at home." },
    { id: 39, spanish: "seguir", english: "to follow/continue", example: "Sigue todo recto.", translation: "Continue straight ahead." },
    { id: 40, spanish: "encontrar", english: "to find", example: "No puedo encontrar mis llaves.", translation: "I can't find my keys." },
    { id: 41, spanish: "buscar", english: "to look for/search", example: "Busco un apartamento nuevo.", translation: "I'm looking for a new apartment." },
    { id: 42, spanish: "llevar", english: "to carry/wear/take", example: "Llevo una chaqueta azul.", translation: "I'm wearing a blue jacket." },
    { id: 43, spanish: "traer", english: "to bring", example: "Trae tu pasaporte.", translation: "Bring your passport." },
    { id: 44, spanish: "pensar", english: "to think", example: "¿Qué piensas de esta idea?", translation: "What do you think of this idea?" },
    { id: 45, spanish: "creer", english: "to believe", example: "Creo que tienes razón.", translation: "I think you're right." },
    { id: 46, spanish: "sentir", english: "to feel", example: "Me siento muy feliz hoy.", translation: "I feel very happy today." },
    { id: 47, spanish: "parecer", english: "to seem/appear", example: "Parece que va a llover.", translation: "It seems like it's going to rain." },
    { id: 48, spanish: "vivir", english: "to live", example: "Vivo en Barcelona.", translation: "I live in Barcelona." },
    { id: 49, spanish: "morir", english: "to die", example: "La planta murió sin agua.", translation: "The plant died without water." },
    { id: 50, spanish: "comer", english: "to eat", example: "Vamos a comer juntos.", translation: "We're going to eat together." },
    { id: 51, spanish: "beber", english: "to drink", example: "¿Quieres beber algo?", translation: "Do you want to drink something?" },
    { id: 52, spanish: "hablar", english: "to speak/talk", example: "Hablo español e inglés.", translation: "I speak Spanish and English." },
    { id: 53, spanish: "escribir", english: "to write", example: "Escribo una carta.", translation: "I'm writing a letter." },
    { id: 54, spanish: "leer", english: "to read", example: "Leo un libro interesante.", translation: "I'm reading an interesting book." },
    { id: 55, spanish: "escuchar", english: "to listen", example: "Escucho música todas las noches.", translation: "I listen to music every night." },
    { id: 56, spanish: "mirar", english: "to look at/watch", example: "Miro el paisaje.", translation: "I'm looking at the landscape." },
    { id: 57, spanish: "trabajar", english: "to work", example: "Trabajo en una empresa.", translation: "I work at a company." },
    { id: 58, spanish: "estudiar", english: "to study", example: "Estudio español cada día.", translation: "I study Spanish every day." },
    { id: 59, spanish: "enseñar", english: "to teach", example: "Enseño matemáticas.", translation: "I teach mathematics." },
    { id: 60, spanish: "aprender", english: "to learn", example: "Aprendo algo nuevo cada día.", translation: "I learn something new every day." },
    { id: 61, spanish: "comprar", english: "to buy", example: "Compro pan en la panadería.", translation: "I buy bread at the bakery." },
    { id: 62, spanish: "vender", english: "to sell", example: "Venden frutas frescas.", translation: "They sell fresh fruits." },
    { id: 63, spanish: "pagar", english: "to pay", example: "Pago en efectivo.", translation: "I pay in cash." },
    { id: 64, spanish: "gastar", english: "to spend (money)", example: "Gasto mucho en comida.", translation: "I spend a lot on food." },
    { id: 65, spanish: "dormir", english: "to sleep", example: "Necesito dormir más.", translation: "I need to sleep more." },
    { id: 66, spanish: "despertar", english: "to wake up", example: "Me despierto a las seis.", translation: "I wake up at six." },
    { id: 67, spanish: "llamar", english: "to call", example: "Voy a llamar a mi madre.", translation: "I'm going to call my mother." },
    { id: 68, spanish: "responder", english: "to answer", example: "No responde al teléfono.", translation: "He/She doesn't answer the phone." },
    { id: 69, spanish: "preguntar", english: "to ask", example: "Voy a preguntar la dirección.", translation: "I'm going to ask for directions." },
    { id: 70, spanish: "contestar", english: "to answer", example: "Contesta las preguntas.", translation: "Answer the questions." },
    { id: 71, spanish: "abrir", english: "to open", example: "Abro la ventana.", translation: "I open the window." },
    { id: 72, spanish: "cerrar", english: "to close", example: "Cierra la puerta.", translation: "Close the door." },
    { id: 73, spanish: "empezar", english: "to begin/start", example: "Empezamos a las nueve.", translation: "We start at nine." },
    { id: 74, spanish: "terminar", english: "to finish/end", example: "Termino el trabajo hoy.", translation: "I finish the work today." },
    { id: 75, spanish: "cambiar", english: "to change", example: "Cambio de opinión.", translation: "I change my mind." },
    { id: 76, spanish: "ayudar", english: "to help", example: "Te puedo ayudar.", translation: "I can help you." },
    { id: 77, spanish: "necesitar", english: "to need", example: "Necesito un favor.", translation: "I need a favor." },
    { id: 78, spanish: "usar", english: "to use", example: "Uso mi teléfono mucho.", translation: "I use my phone a lot." },
    { id: 79, spanish: "jugar", english: "to play", example: "Juego al fútbol los sábados.", translation: "I play soccer on Saturdays." },
    { id: 80, spanish: "cantar", english: "to sing", example: "Ella canta muy bien.", translation: "She sings very well." },

    // Common Nouns - People & Family (81-110)
    { id: 81, spanish: "persona", english: "person", example: "Ella es una persona amable.", translation: "She is a kind person." },
    { id: 82, spanish: "gente", english: "people", example: "Hay mucha gente aquí.", translation: "There are many people here." },
    { id: 83, spanish: "hombre", english: "man", example: "El hombre camina por la calle.", translation: "The man walks down the street." },
    { id: 84, spanish: "mujer", english: "woman", example: "La mujer trabaja en una oficina.", translation: "The woman works in an office." },
    { id: 85, spanish: "niño", english: "child/boy", example: "El niño juega en el parque.", translation: "The child plays in the park." },
    { id: 86, spanish: "niña", english: "girl", example: "La niña lee un cuento.", translation: "The girl reads a story." },
    { id: 87, spanish: "bebé", english: "baby", example: "El bebé llora mucho.", translation: "The baby cries a lot." },
    { id: 88, spanish: "familia", english: "family", example: "Mi familia es muy importante.", translation: "My family is very important." },
    { id: 89, spanish: "padre", english: "father", example: "Mi padre es médico.", translation: "My father is a doctor." },
    { id: 90, spanish: "madre", english: "mother", example: "Mi madre cocina muy bien.", translation: "My mother cooks very well." },
    { id: 91, spanish: "hijo", english: "son", example: "Tengo un hijo pequeño.", translation: "I have a young son." },
    { id: 92, spanish: "hija", english: "daughter", example: "Mi hija estudia medicina.", translation: "My daughter studies medicine." },
    { id: 93, spanish: "hermano", english: "brother", example: "Mi hermano vive en Madrid.", translation: "My brother lives in Madrid." },
    { id: 94, spanish: "hermana", english: "sister", example: "Mi hermana es profesora.", translation: "My sister is a teacher." },
    { id: 95, spanish: "abuelo", english: "grandfather", example: "Mi abuelo tiene ochenta años.", translation: "My grandfather is eighty years old." },
    { id: 96, spanish: "abuela", english: "grandmother", example: "Mi abuela cocina delicioso.", translation: "My grandmother cooks delicious food." },
    { id: 97, spanish: "tío", english: "uncle", example: "Mi tío es ingeniero.", translation: "My uncle is an engineer." },
    { id: 98, spanish: "tía", english: "aunt", example: "Mi tía vive en Barcelona.", translation: "My aunt lives in Barcelona." },
    { id: 99, spanish: "primo", english: "cousin (male)", example: "Mi primo juega al fútbol.", translation: "My cousin plays soccer." },
    { id: 100, spanish: "prima", english: "cousin (female)", example: "Mi prima es artista.", translation: "My cousin is an artist." },
    { id: 101, spanish: "esposo", english: "husband", example: "Mi esposo trabaja en casa.", translation: "My husband works at home." },
    { id: 102, spanish: "esposa", english: "wife", example: "Mi esposa es abogada.", translation: "My wife is a lawyer." },
    { id: 103, spanish: "novio", english: "boyfriend", example: "Mi novio es muy romántico.", translation: "My boyfriend is very romantic." },
    { id: 104, spanish: "novia", english: "girlfriend", example: "Mi novia estudia arquitectura.", translation: "My girlfriend studies architecture." },
    { id: 105, spanish: "amigo", english: "friend (male)", example: "Él es mi mejor amigo.", translation: "He is my best friend." },
    { id: 106, spanish: "amiga", english: "friend (female)", example: "Ella es mi amiga de la infancia.", translation: "She is my childhood friend." },
    { id: 107, spanish: "vecino", english: "neighbor (male)", example: "Mi vecino es muy amable.", translation: "My neighbor is very kind." },
    { id: 108, spanish: "vecina", english: "neighbor (female)", example: "Mi vecina tiene un perro.", translation: "My neighbor has a dog." },
    { id: 109, spanish: "compañero", english: "companion/classmate", example: "Es mi compañero de clase.", translation: "He's my classmate." },
    { id: 110, spanish: "jefe", english: "boss", example: "Mi jefe es muy estricto.", translation: "My boss is very strict." },

    // Common Nouns - Places (111-140)
    { id: 111, spanish: "casa", english: "house/home", example: "Mi casa es grande.", translation: "My house is big." },
    { id: 112, spanish: "apartamento", english: "apartment", example: "Vivo en un apartamento pequeño.", translation: "I live in a small apartment." },
    { id: 113, spanish: "edificio", english: "building", example: "El edificio es muy alto.", translation: "The building is very tall." },
    { id: 114, spanish: "ciudad", english: "city", example: "Vivo en una ciudad grande.", translation: "I live in a big city." },
    { id: 115, spanish: "pueblo", english: "town/village", example: "Es un pueblo tranquilo.", translation: "It's a quiet town." },
    { id: 116, spanish: "país", english: "country", example: "España es un país hermoso.", translation: "Spain is a beautiful country." },
    { id: 117, spanish: "calle", english: "street", example: "Vivo en esta calle.", translation: "I live on this street." },
    { id: 118, spanish: "avenida", english: "avenue", example: "La avenida es muy ancha.", translation: "The avenue is very wide." },
    { id: 119, spanish: "plaza", english: "plaza/square", example: "Nos vemos en la plaza.", translation: "We'll meet at the plaza." },
    { id: 120, spanish: "parque", english: "park", example: "Camino en el parque.", translation: "I walk in the park." },
    { id: 121, spanish: "escuela", english: "school", example: "Los niños van a la escuela.", translation: "The children go to school." },
    { id: 122, spanish: "universidad", english: "university", example: "Estudio en la universidad.", translation: "I study at the university." },
    { id: 123, spanish: "hospital", english: "hospital", example: "El hospital está cerca.", translation: "The hospital is nearby." },
    { id: 124, spanish: "restaurante", english: "restaurant", example: "Comemos en un restaurante.", translation: "We eat at a restaurant." },
    { id: 125, spanish: "café", english: "café/coffee", example: "Tomo café en la mañana.", translation: "I drink coffee in the morning." },
    { id: 126, spanish: "tienda", english: "store/shop", example: "Compro en esa tienda.", translation: "I shop at that store." },
    { id: 127, spanish: "supermercado", english: "supermarket", example: "Voy al supermercado.", translation: "I'm going to the supermarket." },
    { id: 128, spanish: "mercado", english: "market", example: "El mercado está abierto.", translation: "The market is open." },
    { id: 129, spanish: "banco", english: "bank/bench", example: "Voy al banco mañana.", translation: "I'm going to the bank tomorrow." },
    { id: 130, spanish: "oficina", english: "office", example: "Trabajo en una oficina.", translation: "I work in an office." },
    { id: 131, spanish: "iglesia", english: "church", example: "La iglesia es antigua.", translation: "The church is old." },
    { id: 132, spanish: "biblioteca", english: "library", example: "Estudio en la biblioteca.", translation: "I study at the library." },
    { id: 133, spanish: "museo", english: "museum", example: "Visitamos el museo.", translation: "We visit the museum." },
    { id: 134, spanish: "cine", english: "cinema/movie theater", example: "Vamos al cine esta noche.", translation: "We're going to the movies tonight." },
    { id: 135, spanish: "teatro", english: "theater", example: "Me gusta ir al teatro.", translation: "I like going to the theater." },
    { id: 136, spanish: "hotel", english: "hotel", example: "Me quedo en un hotel.", translation: "I'm staying at a hotel." },
    { id: 137, spanish: "aeropuerto", english: "airport", example: "Voy al aeropuerto temprano.", translation: "I'm going to the airport early." },
    { id: 138, spanish: "estación", english: "station", example: "La estación de tren está lejos.", translation: "The train station is far." },
    { id: 139, spanish: "playa", english: "beach", example: "Me encanta la playa.", translation: "I love the beach." },
    { id: 140, spanish: "montaña", english: "mountain", example: "La montaña es muy alta.", translation: "The mountain is very tall." },

    // Common Nouns - Things & Objects (141-180)
    { id: 141, spanish: "cosa", english: "thing", example: "Tengo que hacer una cosa.", translation: "I have to do one thing." },
    { id: 142, spanish: "libro", english: "book", example: "Estoy leyendo un libro interesante.", translation: "I'm reading an interesting book." },
    { id: 143, spanish: "mesa", english: "table", example: "La mesa es de madera.", translation: "The table is made of wood." },
    { id: 144, spanish: "silla", english: "chair", example: "Siéntate en esta silla.", translation: "Sit in this chair." },
    { id: 145, spanish: "puerta", english: "door", example: "Cierra la puerta, por favor.", translation: "Close the door, please." },
    { id: 146, spanish: "ventana", english: "window", example: "Abro la ventana para ventilar.", translation: "I open the window to ventilate." },
    { id: 147, spanish: "pared", english: "wall", example: "La pared es blanca.", translation: "The wall is white." },
    { id: 148, spanish: "suelo", english: "floor/ground", example: "El suelo está mojado.", translation: "The floor is wet." },
    { id: 149, spanish: "techo", english: "ceiling/roof", example: "El techo es alto.", translation: "The ceiling is high." },
    { id: 150, spanish: "cama", english: "bed", example: "Mi cama es muy cómoda.", translation: "My bed is very comfortable." },
    { id: 151, spanish: "sofá", english: "sofa/couch", example: "Me siento en el sofá.", translation: "I sit on the sofa." },
    { id: 152, spanish: "televisión", english: "television", example: "Veo la televisión por la noche.", translation: "I watch television at night." },
    { id: 153, spanish: "teléfono", english: "telephone/phone", example: "Mi teléfono está en la mesa.", translation: "My phone is on the table." },
    { id: 154, spanish: "ordenador", english: "computer", example: "Trabajo con mi ordenador.", translation: "I work with my computer." },
    { id: 155, spanish: "computadora", english: "computer", example: "Mi computadora es nueva.", translation: "My computer is new." },
    { id: 156, spanish: "coche", english: "car", example: "Mi coche es rojo.", translation: "My car is red." },
    { id: 157, spanish: "auto", english: "car", example: "Necesito lavar el auto.", translation: "I need to wash the car." },
    { id: 158, spanish: "bicicleta", english: "bicycle", example: "Voy en bicicleta al trabajo.", translation: "I go to work by bicycle." },
    { id: 159, spanish: "moto", english: "motorcycle", example: "Tengo una moto pequeña.", translation: "I have a small motorcycle." },
    { id: 160, spanish: "tren", english: "train", example: "Viajo en tren a Madrid.", translation: "I travel to Madrid by train." },
    { id: 161, spanish: "autobús", english: "bus", example: "Tomo el autobús cada día.", translation: "I take the bus every day." },
    { id: 162, spanish: "avión", english: "airplane", example: "El avión llega a las tres.", translation: "The airplane arrives at three." },
    { id: 163, spanish: "barco", english: "boat/ship", example: "Viajamos en barco.", translation: "We travel by boat." },
    { id: 164, spanish: "reloj", english: "clock/watch", example: "Mi reloj está roto.", translation: "My watch is broken." },
    { id: 165, spanish: "bolsa", english: "bag/purse", example: "Mi bolsa es negra.", translation: "My bag is black." },
    { id: 166, spanish: "mochila", english: "backpack", example: "Llevo mi mochila a la escuela.", translation: "I carry my backpack to school." },
    { id: 167, spanish: "llave", english: "key", example: "No encuentro mis llaves.", translation: "I can't find my keys." },
    { id: 168, spanish: "dinero", english: "money", example: "No tengo mucho dinero.", translation: "I don't have much money." },
    { id: 169, spanish: "tarjeta", english: "card", example: "Pago con tarjeta.", translation: "I pay with card." },
    { id: 170, spanish: "papel", english: "paper", example: "Necesito un papel y un lápiz.", translation: "I need a paper and a pencil." },
    { id: 171, spanish: "lápiz", english: "pencil", example: "Escribo con un lápiz.", translation: "I write with a pencil." },
    { id: 172, spanish: "pluma", english: "pen", example: "Mi pluma no funciona.", translation: "My pen doesn't work." },
    { id: 173, spanish: "cuaderno", english: "notebook", example: "Escribo en mi cuaderno.", translation: "I write in my notebook." },
    { id: 174, spanish: "ropa", english: "clothes/clothing", example: "Compro ropa nueva.", translation: "I buy new clothes." },
    { id: 175, spanish: "camisa", english: "shirt", example: "Llevo una camisa azul.", translation: "I'm wearing a blue shirt." },
    { id: 176, spanish: "pantalón", english: "pants", example: "Mis pantalones son negros.", translation: "My pants are black." },
    { id: 177, spanish: "zapato", english: "shoe", example: "Necesito zapatos nuevos.", translation: "I need new shoes." },
    { id: 178, spanish: "sombrero", english: "hat", example: "Llevo un sombrero para el sol.", translation: "I wear a hat for the sun." },
    { id: 179, spanish: "gafas", english: "glasses", example: "Uso gafas para leer.", translation: "I use glasses to read." },
    { id: 180, spanish: "reloj", english: "watch/clock", example: "¿Qué hora marca tu reloj?", translation: "What time does your watch show?" },

    // Food & Drink (181-220)
    { id: 181, spanish: "comida", english: "food", example: "La comida está deliciosa.", translation: "The food is delicious." },
    { id: 182, spanish: "bebida", english: "drink/beverage", example: "¿Qué bebida prefieres?", translation: "What drink do you prefer?" },
    { id: 183, spanish: "agua", english: "water", example: "Necesito un vaso de agua.", translation: "I need a glass of water." },
    { id: 184, spanish: "leche", english: "milk", example: "Tomo leche en el desayuno.", translation: "I drink milk at breakfast." },
    { id: 185, spanish: "café", english: "coffee", example: "Me encanta el café.", translation: "I love coffee." },
    { id: 186, spanish: "té", english: "tea", example: "Bebo té verde.", translation: "I drink green tea." },
    { id: 187, spanish: "jugo", english: "juice", example: "Quiero jugo de naranja.", translation: "I want orange juice." },
    { id: 188, spanish: "vino", english: "wine", example: "Tomamos vino con la cena.", translation: "We have wine with dinner." },
    { id: 189, spanish: "cerveza", english: "beer", example: "Una cerveza fría, por favor.", translation: "A cold beer, please." },
    { id: 190, spanish: "pan", english: "bread", example: "Compro pan fresco.", translation: "I buy fresh bread." },
    { id: 191, spanish: "arroz", english: "rice", example: "Comemos arroz con pollo.", translation: "We eat rice with chicken." },
    { id: 192, spanish: "pasta", english: "pasta", example: "Me gusta la pasta italiana.", translation: "I like Italian pasta." },
    { id: 193, spanish: "carne", english: "meat", example: "No como mucha carne.", translation: "I don't eat much meat." },
    { id: 194, spanish: "pollo", english: "chicken", example: "El pollo está bien cocido.", translation: "The chicken is well cooked." },
    { id: 195, spanish: "pescado", english: "fish", example: "Como pescado dos veces por semana.", translation: "I eat fish twice a week." },
    { id: 196, spanish: "huevo", english: "egg", example: "Desayuno huevos revueltos.", translation: "I have scrambled eggs for breakfast." },
    { id: 197, spanish: "queso", english: "cheese", example: "Me encanta el queso.", translation: "I love cheese." },
    { id: 198, spanish: "mantequilla", english: "butter", example: "Pon mantequilla en el pan.", translation: "Put butter on the bread." },
    { id: 199, spanish: "azúcar", english: "sugar", example: "¿Quieres azúcar en el café?", translation: "Do you want sugar in your coffee?" },
    { id: 200, spanish: "sal", english: "salt", example: "Pasa la sal, por favor.", translation: "Pass the salt, please." },
    { id: 201, spanish: "fruta", english: "fruit", example: "Como fruta todos los días.", translation: "I eat fruit every day." },
    { id: 202, spanish: "manzana", english: "apple", example: "Una manzana al día es saludable.", translation: "An apple a day is healthy." },
    { id: 203, spanish: "naranja", english: "orange", example: "Las naranjas son ricas en vitamina C.", translation: "Oranges are rich in vitamin C." },
    { id: 204, spanish: "plátano", english: "banana", example: "Los plátanos tienen potasio.", translation: "Bananas have potassium." },
    { id: 205, spanish: "fresa", english: "strawberry", example: "Me encantan las fresas.", translation: "I love strawberries." },
    { id: 206, spanish: "uva", english: "grape", example: "Comemos uvas en año nuevo.", translation: "We eat grapes on New Year's." },
    { id: 207, spanish: "verdura", english: "vegetable", example: "Las verduras son nutritivas.", translation: "Vegetables are nutritious." },
    { id: 208, spanish: "ensalada", english: "salad", example: "Preparo una ensalada fresca.", translation: "I prepare a fresh salad." },
    { id: 209, spanish: "tomate", english: "tomato", example: "Los tomates están maduros.", translation: "The tomatoes are ripe." },
    { id: 210, spanish: "lechuga", english: "lettuce", example: "La lechuga está en el refrigerador.", translation: "The lettuce is in the refrigerator." },
    { id: 211, spanish: "zanahoria", english: "carrot", example: "Las zanahorias son buenas para la vista.", translation: "Carrots are good for eyesight." },
    { id: 212, spanish: "cebolla", english: "onion", example: "La cebolla me hace llorar.", translation: "The onion makes me cry." },
    { id: 213, spanish: "papa", english: "potato", example: "Me gustan las papas fritas.", translation: "I like french fries." },
    { id: 214, spanish: "patata", english: "potato", example: "Hago tortilla de patatas.", translation: "I make potato omelette." },
    { id: 215, spanish: "sopa", english: "soup", example: "La sopa está caliente.", translation: "The soup is hot." },
    { id: 216, spanish: "postre", english: "dessert", example: "¿Qué hay de postre?", translation: "What's for dessert?" },
    { id: 217, spanish: "pastel", english: "cake", example: "El pastel de chocolate es delicioso.", translation: "The chocolate cake is delicious." },
    { id: 218, spanish: "helado", english: "ice cream", example: "Me encanta el helado de vainilla.", translation: "I love vanilla ice cream." },
    { id: 219, spanish: "chocolate", english: "chocolate", example: "El chocolate es mi debilidad.", translation: "Chocolate is my weakness." },
    { id: 220, spanish: "galleta", english: "cookie", example: "Como galletas con leche.", translation: "I eat cookies with milk." },

    // Adjectives - Descriptive (221-280)
    { id: 221, spanish: "bueno", english: "good", example: "Es un buen restaurante.", translation: "It's a good restaurant." },
    { id: 222, spanish: "malo", english: "bad", example: "Hace mal tiempo hoy.", translation: "The weather is bad today." },
    { id: 223, spanish: "grande", english: "big/large", example: "Tengo un problema grande.", translation: "I have a big problem." },
    { id: 224, spanish: "pequeño", english: "small", example: "Mi perro es pequeño.", translation: "My dog is small." },
    { id: 225, spanish: "nuevo", english: "new", example: "Tengo un teléfono nuevo.", translation: "I have a new phone." },
    { id: 226, spanish: "viejo", english: "old", example: "Este edificio es muy viejo.", translation: "This building is very old." },
    { id: 227, spanish: "joven", english: "young", example: "Soy muy joven todavía.", translation: "I'm still very young." },
    { id: 228, spanish: "bonito", english: "pretty/beautiful", example: "Qué bonito vestido.", translation: "What a pretty dress." },
    { id: 229, spanish: "feo", english: "ugly", example: "El edificio es feo.", translation: "The building is ugly." },
    { id: 230, spanish: "hermoso", english: "beautiful", example: "El paisaje es hermoso.", translation: "The landscape is beautiful." },
    { id: 231, spanish: "lindo", english: "cute/pretty", example: "Tienes un perro muy lindo.", translation: "You have a very cute dog." },
    { id: 232, spanish: "alto", english: "tall/high", example: "El edificio es muy alto.", translation: "The building is very tall." },
    { id: 233, spanish: "bajo", english: "short/low", example: "Soy bajo de estatura.", translation: "I'm short in height." },
    { id: 234, spanish: "largo", english: "long", example: "Tengo el pelo largo.", translation: "I have long hair." },
    { id: 235, spanish: "corto", english: "short", example: "El vestido es muy corto.", translation: "The dress is very short." },
    { id: 236, spanish: "gordo", english: "fat", example: "El gato está gordo.", translation: "The cat is fat." },
    { id: 237, spanish: "delgado", english: "thin/slim", example: "Ella es muy delgada.", translation: "She is very thin." },
    { id: 238, spanish: "fuerte", english: "strong", example: "Él es muy fuerte.", translation: "He is very strong." },
    { id: 239, spanish: "débil", english: "weak", example: "Me siento débil hoy.", translation: "I feel weak today." },
    { id: 240, spanish: "rápido", english: "fast", example: "El coche es muy rápido.", translation: "The car is very fast." },
    { id: 241, spanish: "lento", english: "slow", example: "El tren es lento.", translation: "The train is slow." },
    { id: 242, spanish: "fácil", english: "easy", example: "El examen es fácil.", translation: "The exam is easy." },
    { id: 243, spanish: "difícil", english: "difficult/hard", example: "El problema es difícil.", translation: "The problem is difficult." },
    { id: 244, spanish: "feliz", english: "happy", example: "Estoy muy feliz hoy.", translation: "I'm very happy today." },
    { id: 245, spanish: "triste", english: "sad", example: "Ella está triste.", translation: "She is sad." },
    { id: 246, spanish: "contento", english: "content/happy", example: "Estoy contento con el resultado.", translation: "I'm happy with the result." },
    { id: 247, spanish: "enojado", english: "angry", example: "Está muy enojado conmigo.", translation: "He's very angry with me." },
    { id: 248, spanish: "cansado", english: "tired", example: "Estoy muy cansado.", translation: "I'm very tired." },
    { id: 249, spanish: "aburrido", english: "bored/boring", example: "Estoy muy aburrido.", translation: "I'm very bored." },
    { id: 250, spanish: "interesante", english: "interesting", example: "El libro es muy interesante.", translation: "The book is very interesting." },
    { id: 251, spanish: "importante", english: "important", example: "Es muy importante estudiar.", translation: "It's very important to study." },
    { id: 252, spanish: "necesario", english: "necessary", example: "Es necesario practicar.", translation: "It's necessary to practice." },
    { id: 253, spanish: "posible", english: "possible", example: "Es posible llegar a tiempo.", translation: "It's possible to arrive on time." },
    { id: 254, spanish: "imposible", english: "impossible", example: "Es imposible terminar hoy.", translation: "It's impossible to finish today." },
    { id: 255, spanish: "seguro", english: "sure/safe", example: "Estoy seguro de eso.", translation: "I'm sure of that." },
    { id: 256, spanish: "peligroso", english: "dangerous", example: "Es muy peligroso.", translation: "It's very dangerous." },
    { id: 257, spanish: "rico", english: "rich/delicious", example: "La comida está muy rica.", translation: "The food is very delicious." },
    { id: 258, spanish: "pobre", english: "poor", example: "Es un país pobre.", translation: "It's a poor country." },
    { id: 259, spanish: "caro", english: "expensive", example: "El restaurante es muy caro.", translation: "The restaurant is very expensive." },
    { id: 260, spanish: "barato", english: "cheap", example: "Estos zapatos son baratos.", translation: "These shoes are cheap." },
    { id: 261, spanish: "limpio", english: "clean", example: "La casa está limpia.", translation: "The house is clean." },
    { id: 262, spanish: "sucio", english: "dirty", example: "El coche está sucio.", translation: "The car is dirty." },
    { id: 263, spanish: "caliente", english: "hot", example: "El café está caliente.", translation: "The coffee is hot." },
    { id: 264, spanish: "frío", english: "cold", example: "El agua está fría.", translation: "The water is cold." },
    { id: 265, spanish: "calor", english: "heat/hot", example: "Tengo mucho calor.", translation: "I'm very hot." },
    { id: 266, spanish: "frío", english: "cold", example: "Tengo mucho frío.", translation: "I'm very cold." },
    { id: 267, spanish: "lleno", english: "full", example: "El vaso está lleno.", translation: "The glass is full." },
    { id: 268, spanish: "vacío", english: "empty", example: "La botella está vacía.", translation: "The bottle is empty." },
    { id: 269, spanish: "abierto", english: "open", example: "La puerta está abierta.", translation: "The door is open." },
    { id: 270, spanish: "cerrado", english: "closed", example: "El banco está cerrado.", translation: "The bank is closed." },
    { id: 271, spanish: "roto", english: "broken", example: "Mi reloj está roto.", translation: "My watch is broken." },
    { id: 272, spanish: "ruidoso", english: "noisy/loud", example: "La ciudad es ruidosa.", translation: "The city is noisy." },
    { id: 273, spanish: "tranquilo", english: "calm/quiet", example: "Es un lugar tranquilo.", translation: "It's a quiet place." },
    { id: 274, spanish: "ocupado", english: "busy/occupied", example: "Estoy muy ocupado hoy.", translation: "I'm very busy today." },
    { id: 275, spanish: "libre", english: "free", example: "Estoy libre esta noche.", translation: "I'm free tonight." },
    { id: 276, spanish: "listo", english: "ready/smart", example: "Estoy listo para salir.", translation: "I'm ready to leave." },
    { id: 277, spanish: "simple", english: "simple", example: "Es una receta simple.", translation: "It's a simple recipe." },
    { id: 278, spanish: "complicado", english: "complicated", example: "El problema es complicado.", translation: "The problem is complicated." },
    { id: 279, spanish: "diferente", english: "different", example: "Somos muy diferentes.", translation: "We are very different." },
    { id: 280, spanish: "igual", english: "equal/same", example: "Todos somos iguales.", translation: "We are all equal." },

    // Colors (281-295)
    { id: 281, spanish: "color", english: "color", example: "¿Cuál es tu color favorito?", translation: "What's your favorite color?" },
    { id: 282, spanish: "blanco", english: "white", example: "La nieve es blanca.", translation: "Snow is white." },
    { id: 283, spanish: "negro", english: "black", example: "Llevo zapatos negros.", translation: "I'm wearing black shoes." },
    { id: 284, spanish: "rojo", english: "red", example: "Mi coche es rojo.", translation: "My car is red." },
    { id: 285, spanish: "azul", english: "blue", example: "El cielo es azul.", translation: "The sky is blue." },
    { id: 286, spanish: "verde", english: "green", example: "La hierba es verde.", translation: "The grass is green." },
    { id: 287, spanish: "amarillo", english: "yellow", example: "El sol es amarillo.", translation: "The sun is yellow." },
    { id: 288, spanish: "naranja", english: "orange (color)", example: "La naranja es de color naranja.", translation: "The orange is orange colored." },
    { id: 289, spanish: "rosa", english: "pink", example: "Me gusta el rosa.", translation: "I like pink." },
    { id: 290, spanish: "morado", english: "purple", example: "Llevo una camisa morada.", translation: "I'm wearing a purple shirt." },
    { id: 291, spanish: "gris", english: "gray", example: "El gato es gris.", translation: "The cat is gray." },
    { id: 292, spanish: "marrón", english: "brown", example: "Tengo ojos marrones.", translation: "I have brown eyes." },
    { id: 293, spanish: "dorado", english: "golden", example: "El anillo es dorado.", translation: "The ring is golden." },
    { id: 294, spanish: "plateado", english: "silver", example: "El coche es plateado.", translation: "The car is silver." },
    { id: 295, spanish: "claro", english: "light/clear", example: "Prefiero colores claros.", translation: "I prefer light colors." },

    // Time & Date (296-330)
    { id: 296, spanish: "tiempo", english: "time/weather", example: "No tengo tiempo ahora.", translation: "I don't have time now." },
    { id: 297, spanish: "hora", english: "hour/time", example: "¿Qué hora es?", translation: "What time is it?" },
    { id: 298, spanish: "día", english: "day", example: "Hoy es un buen día.", translation: "Today is a good day." },
    { id: 299, spanish: "noche", english: "night", example: "Buenas noches, hasta mañana.", translation: "Good night, see you tomorrow." },
    { id: 300, spanish: "mañana", english: "tomorrow/morning", example: "Nos vemos mañana.", translation: "See you tomorrow." },
    { id: 301, spanish: "tarde", english: "afternoon/late", example: "Buenas tardes.", translation: "Good afternoon." },
    { id: 302, spanish: "semana", english: "week", example: "Esta semana estoy ocupado.", translation: "This week I'm busy." },
    { id: 303, spanish: "mes", english: "month", example: "El próximo mes es enero.", translation: "Next month is January." },
    { id: 304, spanish: "año", english: "year", example: "Este año voy a España.", translation: "This year I'm going to Spain." },
    { id: 305, spanish: "hoy", english: "today", example: "Hoy hace buen tiempo.", translation: "The weather is good today." },
    { id: 306, spanish: "ayer", english: "yesterday", example: "Ayer fui al cine.", translation: "Yesterday I went to the movies." },
    { id: 307, spanish: "ahora", english: "now", example: "Tengo que irme ahora.", translation: "I have to go now." },
    { id: 308, spanish: "después", english: "after/later", example: "Hablamos después.", translation: "We'll talk later." },
    { id: 309, spanish: "antes", english: "before", example: "Llegué antes que tú.", translation: "I arrived before you." },
    { id: 310, spanish: "siempre", english: "always", example: "Siempre llego tarde.", translation: "I always arrive late." },
    { id: 311, spanish: "nunca", english: "never", example: "Nunca he estado en París.", translation: "I've never been to Paris." },
    { id: 312, spanish: "a veces", english: "sometimes", example: "A veces voy al gimnasio.", translation: "Sometimes I go to the gym." },
    { id: 313, spanish: "pronto", english: "soon", example: "Regreso pronto.", translation: "I'll return soon." },
    { id: 314, spanish: "temprano", english: "early", example: "Me levanto temprano.", translation: "I wake up early." },
    { id: 315, spanish: "tarde", english: "late", example: "Siempre llego tarde.", translation: "I always arrive late." },
    { id: 316, spanish: "lunes", english: "Monday", example: "El lunes voy al trabajo.", translation: "On Monday I go to work." },
    { id: 317, spanish: "martes", english: "Tuesday", example: "Martes es mi día favorito.", translation: "Tuesday is my favorite day." },
    { id: 318, spanish: "miércoles", english: "Wednesday", example: "El miércoles tengo clase.", translation: "On Wednesday I have class." },
    { id: 319, spanish: "jueves", english: "Thursday", example: "Jueves voy al gimnasio.", translation: "Thursday I go to the gym." },
    { id: 320, spanish: "viernes", english: "Friday", example: "El viernes salgo con amigos.", translation: "On Friday I go out with friends." },
    { id: 321, spanish: "sábado", english: "Saturday", example: "Sábado descanso en casa.", translation: "Saturday I rest at home." },
    { id: 322, spanish: "domingo", english: "Sunday", example: "Domingo voy a la iglesia.", translation: "Sunday I go to church." },
    { id: 323, spanish: "enero", english: "January", example: "Enero es el primer mes.", translation: "January is the first month." },
    { id: 324, spanish: "febrero", english: "February", example: "En febrero hace frío.", translation: "In February it's cold." },
    { id: 325, spanish: "marzo", english: "March", example: "Marzo llega la primavera.", translation: "Spring comes in March." },
    { id: 326, spanish: "abril", english: "April", example: "En abril llueve mucho.", translation: "In April it rains a lot." },
    { id: 327, spanish: "mayo", english: "May", example: "Mayo es un mes bonito.", translation: "May is a nice month." },
    { id: 328, spanish: "junio", english: "June", example: "En junio empieza el verano.", translation: "Summer starts in June." },
    { id: 329, spanish: "julio", english: "July", example: "Julio es muy caluroso.", translation: "July is very hot." },
    { id: 330, spanish: "agosto", english: "August", example: "Agosto voy de vacaciones.", translation: "In August I go on vacation." },

    // More Common Words & Expressions (331-400)
    { id: 331, spanish: "septiembre", english: "September", example: "Septiembre vuelvo a trabajar.", translation: "In September I return to work." },
    { id: 332, spanish: "octubre", english: "October", example: "Octubre es mi mes favorito.", translation: "October is my favorite month." },
    { id: 333, spanish: "noviembre", english: "November", example: "En noviembre hace frío.", translation: "In November it's cold." },
    { id: 334, spanish: "diciembre", english: "December", example: "Diciembre es navidad.", translation: "December is Christmas." },
    { id: 335, spanish: "primavera", english: "spring", example: "Me encanta la primavera.", translation: "I love spring." },
    { id: 336, spanish: "verano", english: "summer", example: "El verano es muy caluroso.", translation: "Summer is very hot." },
    { id: 337, spanish: "otoño", english: "autumn/fall", example: "En otoño caen las hojas.", translation: "In autumn the leaves fall." },
    { id: 338, spanish: "invierno", english: "winter", example: "El invierno es frío.", translation: "Winter is cold." },
    { id: 339, spanish: "mucho", english: "much/a lot", example: "Me gusta mucho el chocolate.", translation: "I like chocolate a lot." },
    { id: 340, spanish: "poco", english: "little/few", example: "Tengo poco dinero.", translation: "I have little money." },
    { id: 341, spanish: "más", english: "more", example: "Quiero más café.", translation: "I want more coffee." },
    { id: 342, spanish: "menos", english: "less", example: "Trabajo menos que antes.", translation: "I work less than before." },
    { id: 343, spanish: "muy", english: "very", example: "Estoy muy cansado.", translation: "I'm very tired." },
    { id: 344, spanish: "bastante", english: "quite/enough", example: "Tengo bastante trabajo.", translation: "I have quite a lot of work." },
    { id: 345, spanish: "demasiado", english: "too much", example: "Hace demasiado calor.", translation: "It's too hot." },
    { id: 346, spanish: "todo", english: "all/everything", example: "Todo está bien.", translation: "Everything is fine." },
    { id: 347, spanish: "nada", english: "nothing", example: "No quiero nada.", translation: "I don't want anything." },
    { id: 348, spanish: "algo", english: "something", example: "Quiero comer algo.", translation: "I want to eat something." },
    { id: 349, spanish: "alguien", english: "someone", example: "Alguien llama a la puerta.", translation: "Someone is knocking on the door." },
    { id: 350, spanish: "nadie", english: "nobody/no one", example: "No hay nadie en casa.", translation: "There's nobody at home." },
    { id: 351, spanish: "bien", english: "well/good", example: "Todo está bien.", translation: "Everything is good." },
    { id: 352, spanish: "mal", english: "badly/bad", example: "Me siento mal.", translation: "I feel bad." },
    { id: 353, spanish: "mejor", english: "better", example: "Hoy me siento mejor.", translation: "Today I feel better." },
    { id: 354, spanish: "peor", english: "worse", example: "Esto es peor.", translation: "This is worse." },
    { id: 355, spanish: "aquí", english: "here", example: "Ven aquí, por favor.", translation: "Come here, please." },
    { id: 356, spanish: "allí", english: "there", example: "El banco está allí.", translation: "The bank is there." },
    { id: 357, spanish: "ahí", english: "there", example: "Está ahí mismo.", translation: "It's right there." },
    { id: 358, spanish: "donde", english: "where", example: "¿Dónde vives?", translation: "Where do you live?" },
    { id: 359, spanish: "cuando", english: "when", example: "¿Cuándo vienes?", translation: "When are you coming?" },
    { id: 360, spanish: "cómo", english: "how", example: "¿Cómo estás?", translation: "How are you?" },
    { id: 361, spanish: "qué", english: "what", example: "¿Qué quieres?", translation: "What do you want?" },
    { id: 362, spanish: "quién", english: "who", example: "¿Quién es?", translation: "Who is it?" },
    { id: 363, spanish: "por qué", english: "why", example: "¿Por qué estudias español?", translation: "Why do you study Spanish?" },
    { id: 364, spanish: "cuál", english: "which/what", example: "¿Cuál prefieres?", translation: "Which do you prefer?" },
    { id: 365, spanish: "cuánto", english: "how much", example: "¿Cuánto cuesta?", translation: "How much does it cost?" },
    { id: 366, spanish: "cuándo", english: "when", example: "¿Cuándo llegaste?", translation: "When did you arrive?" },
    { id: 367, spanish: "este", english: "this (masculine)", example: "Este libro es mío.", translation: "This book is mine." },
    { id: 368, spanish: "esta", english: "this (feminine)", example: "Esta casa es grande.", translation: "This house is big." },
    { id: 369, spanish: "ese", english: "that (masculine)", example: "Ese coche es rojo.", translation: "That car is red." },
    { id: 370, spanish: "esa", english: "that (feminine)", example: "Esa silla es cómoda.", translation: "That chair is comfortable." },
    { id: 371, spanish: "aquel", english: "that over there (m)", example: "Aquel edificio es alto.", translation: "That building over there is tall." },
    { id: 372, spanish: "aquella", english: "that over there (f)", example: "Aquella montaña es hermosa.", translation: "That mountain over there is beautiful." },
    { id: 373, spanish: "mi", english: "my", example: "Mi casa está cerca.", translation: "My house is nearby." },
    { id: 374, spanish: "tu", english: "your (informal)", example: "Tu libro está aquí.", translation: "Your book is here." },
    { id: 375, spanish: "su", english: "his/her/your (formal)", example: "Su coche es nuevo.", translation: "His/Her/Your car is new." },
    { id: 376, spanish: "nuestro", english: "our", example: "Nuestro país es hermoso.", translation: "Our country is beautiful." },
    { id: 377, spanish: "vuestro", english: "your (plural)", example: "Vuestro proyecto es interesante.", translation: "Your project is interesting." },
    { id: 378, spanish: "yo", english: "I", example: "Yo soy de México.", translation: "I am from Mexico." },
    { id: 379, spanish: "tú", english: "you (informal)", example: "¿Tú hablas español?", translation: "Do you speak Spanish?" },
    { id: 380, spanish: "él", english: "he", example: "Él es mi hermano.", translation: "He is my brother." },
    { id: 381, spanish: "ella", english: "she", example: "Ella es doctora.", translation: "She is a doctor." },
    { id: 382, spanish: "nosotros", english: "we", example: "Nosotros somos amigos.", translation: "We are friends." },
    { id: 383, spanish: "vosotros", english: "you (plural)", example: "Vosotros sois españoles.", translation: "You are Spanish." },
    { id: 384, spanish: "ellos", english: "they (masculine)", example: "Ellos juegan al fútbol.", translation: "They play soccer." },
    { id: 385, spanish: "ellas", english: "they (feminine)", example: "Ellas estudian medicina.", translation: "They study medicine." },
    { id: 386, spanish: "me", english: "me", example: "Me gusta el café.", translation: "I like coffee." },
    { id: 387, spanish: "te", english: "you (informal object)", example: "Te quiero mucho.", translation: "I love you very much." },
    { id: 388, spanish: "le", english: "him/her/you (formal)", example: "Le doy el libro.", translation: "I give him/her the book." },
    { id: 389, spanish: "nos", english: "us", example: "Nos vemos mañana.", translation: "We'll see each other tomorrow." },
    { id: 390, spanish: "les", english: "them/you (formal pl)", example: "Les envío un mensaje.", translation: "I send them a message." },
    { id: 391, spanish: "se", english: "reflexive pronoun", example: "Se levanta temprano.", translation: "He/She gets up early." },
    { id: 392, spanish: "con", english: "with", example: "Voy con mis amigos.", translation: "I'm going with my friends." },
    { id: 393, spanish: "sin", english: "without", example: "Café sin azúcar.", translation: "Coffee without sugar." },
    { id: 394, spanish: "para", english: "for/to", example: "Esto es para ti.", translation: "This is for you." },
    { id: 395, spanish: "por", english: "for/by/through", example: "Gracias por tu ayuda.", translation: "Thanks for your help." },
    { id: 396, spanish: "en", english: "in/on/at", example: "Estoy en casa.", translation: "I'm at home." },
    { id: 397, spanish: "de", english: "of/from", example: "Soy de España.", translation: "I'm from Spain." },
    { id: 398, spanish: "a", english: "to/at", example: "Voy a la tienda.", translation: "I'm going to the store." },
    { id: 399, spanish: "desde", english: "from/since", example: "Trabajo desde las ocho.", translation: "I work from eight o'clock." },
    { id: 400, spanish: "hasta", english: "until/to", example: "Hasta luego.", translation: "See you later." },

    // Final 100 words (401-500)
    { id: 401, spanish: "sobre", english: "about/on/over", example: "Hablamos sobre política.", translation: "We talk about politics." },
    { id: 402, spanish: "entre", english: "between/among", example: "Entre tú y yo.", translation: "Between you and me." },
    { id: 403, spanish: "durante", english: "during", example: "Durante el verano viajo.", translation: "During summer I travel." },
    { id: 404, spanish: "contra", english: "against", example: "Juego contra mi hermano.", translation: "I play against my brother." },
    { id: 405, spanish: "bajo", english: "under", example: "El gato está bajo la mesa.", translation: "The cat is under the table." },
    { id: 406, spanish: "tras", english: "after/behind", example: "Tras la puerta.", translation: "Behind the door." },
    { id: 407, spanish: "hacia", english: "toward", example: "Voy hacia el norte.", translation: "I'm going toward the north." },
    { id: 408, spanish: "según", english: "according to", example: "Según el periódico.", translation: "According to the newspaper." },
    { id: 409, spanish: "y", english: "and", example: "Café y pan.", translation: "Coffee and bread." },
    { id: 410, spanish: "o", english: "or", example: "¿Café o té?", translation: "Coffee or tea?" },
    { id: 411, spanish: "pero", english: "but", example: "Quiero ir, pero estoy ocupado.", translation: "I want to go, but I'm busy." },
    { id: 412, spanish: "porque", english: "because", example: "Estudio porque quiero aprender.", translation: "I study because I want to learn." },
    { id: 413, spanish: "si", english: "if", example: "Si puedes, ven.", translation: "If you can, come." },
    { id: 414, spanish: "aunque", english: "although/even though", example: "Aunque llueve, salgo.", translation: "Although it's raining, I'm going out." },
    { id: 415, spanish: "cuando", english: "when", example: "Cuando llegues, llámame.", translation: "When you arrive, call me." },
    { id: 416, spanish: "mientras", english: "while", example: "Mientras cocino, escucho música.", translation: "While I cook, I listen to music." },
    { id: 417, spanish: "como", english: "like/as/how", example: "Como tú quieras.", translation: "As you wish." },
    { id: 418, spanish: "tanto", english: "so much", example: "Te extraño tanto.", translation: "I miss you so much." },
    { id: 419, spanish: "también", english: "also/too", example: "Yo también voy.", translation: "I'm going too." },
    { id: 420, spanish: "tampoco", english: "neither/either", example: "Yo tampoco quiero.", translation: "I don't want to either." },
    { id: 421, spanish: "solo", english: "only/alone", example: "Solo quiero agua.", translation: "I only want water." },
    { id: 422, spanish: "solamente", english: "only", example: "Solamente una vez.", translation: "Only once." },
    { id: 423, spanish: "incluso", english: "even", example: "Incluso los domingos.", translation: "Even on Sundays." },
    { id: 424, spanish: "excepto", english: "except", example: "Todos excepto yo.", translation: "Everyone except me." },
    { id: 425, spanish: "además", english: "besides/moreover", example: "Además, es tarde.", translation: "Besides, it's late." },
    { id: 426, spanish: "entonces", english: "then", example: "Entonces, ¿qué hacemos?", translation: "Then, what do we do?" },
    { id: 427, spanish: "pues", english: "well/then", example: "Pues, no sé.", translation: "Well, I don't know." },
    { id: 428, spanish: "así", english: "like this/thus", example: "Hazlo así.", translation: "Do it like this." },
    { id: 429, spanish: "todavía", english: "still/yet", example: "Todavía no llega.", translation: "He/She hasn't arrived yet." },
    { id: 430, spanish: "ya", english: "already", example: "Ya terminé.", translation: "I already finished." },
    { id: 431, spanish: "aún", english: "still/yet", example: "Aún no sé.", translation: "I still don't know." },
    { id: 432, spanish: "casi", english: "almost", example: "Casi termino.", translation: "I almost finished." },
    { id: 433, spanish: "quizás", english: "maybe/perhaps", example: "Quizás mañana.", translation: "Maybe tomorrow." },
    { id: 434, spanish: "acaso", english: "perhaps/maybe", example: "¿Acaso no me crees?", translation: "Don't you believe me perhaps?" },
    { id: 435, spanish: "apenas", english: "barely/hardly", example: "Apenas puedo ver.", translation: "I can barely see." },
    { id: 436, spanish: "realmente", english: "really", example: "Realmente me gusta.", translation: "I really like it." },
    { id: 437, spanish: "verdaderamente", english: "truly", example: "Verdaderamente hermoso.", translation: "Truly beautiful." },
    { id: 438, spanish: "completamente", english: "completely", example: "Completamente de acuerdo.", translation: "Completely agree." },
    { id: 439, spanish: "totalmente", english: "totally", example: "Totalmente diferente.", translation: "Totally different." },
    { id: 440, spanish: "especialmente", english: "especially", example: "Especialmente para ti.", translation: "Especially for you." },
    { id: 441, spanish: "solamente", english: "only/solely", example: "Solamente tú.", translation: "Only you." },
    { id: 442, spanish: "directamente", english: "directly", example: "Voy directamente a casa.", translation: "I'm going directly home." },
    { id: 443, spanish: "inmediatamente", english: "immediately", example: "Ven inmediatamente.", translation: "Come immediately." },
    { id: 444, spanish: "finalmente", english: "finally", example: "Finalmente llegamos.", translation: "We finally arrived." },
    { id: 445, spanish: "generalmente", english: "generally", example: "Generalmente desayuno temprano.", translation: "I generally have breakfast early." },
    { id: 446, spanish: "normalmente", english: "normally", example: "Normalmente trabajo hasta las seis.", translation: "I normally work until six." },
    { id: 447, spanish: "usualmente", english: "usually", example: "Usualmente camino al trabajo.", translation: "I usually walk to work." },
    { id: 448, spanish: "frecuentemente", english: "frequently", example: "Viajo frecuentemente.", translation: "I travel frequently." },
    { id: 449, spanish: "raramente", english: "rarely", example: "Raramente como carne.", translation: "I rarely eat meat." },
    { id: 450, spanish: "exactamente", english: "exactly", example: "Exactamente lo que necesito.", translation: "Exactly what I need." },
    { id: 451, spanish: "probablemente", english: "probably", example: "Probablemente llueva.", translation: "It will probably rain." },
    { id: 452, spanish: "posiblemente", english: "possibly", example: "Posiblemente llegue tarde.", translation: "I'll possibly arrive late." },
    { id: 453, spanish: "recientemente", english: "recently", example: "Recientemente me mudé.", translation: "I recently moved." },
    { id: 454, spanish: "anteriormente", english: "previously", example: "Anteriormente vivía en Madrid.", translation: "Previously I lived in Madrid." },
    { id: 455, spanish: "actualmente", english: "currently", example: "Actualmente estudio español.", translation: "Currently I study Spanish." },
    { id: 456, spanish: "antiguamente", english: "formerly", example: "Antiguamente había un cine aquí.", translation: "There used to be a cinema here." },
    { id: 457, spanish: "próximamente", english: "soon/shortly", example: "Próximamente en cines.", translation: "Coming soon to theaters." },
    { id: 458, spanish: "constantemente", english: "constantly", example: "Constantemente mejorando.", translation: "Constantly improving." },
    { id: 459, spanish: "perfectamente", english: "perfectly", example: "Entiendo perfectamente.", translation: "I understand perfectly." },
    { id: 460, spanish: "simplemente", english: "simply", example: "Simplemente perfecto.", translation: "Simply perfect." },
    { id: 461, spanish: "lado", english: "side", example: "Al lado de la puerta.", translation: "Next to the door." },
    { id: 462, spanish: "lugar", english: "place", example: "Este es mi lugar favorito.", translation: "This is my favorite place." },
    { id: 463, spanish: "sitio", english: "site/place", example: "Es un sitio interesante.", translation: "It's an interesting place." },
    { id: 464, spanish: "parte", english: "part", example: "La mejor parte del día.", translation: "The best part of the day." },
    { id: 465, spanish: "momento", english: "moment", example: "Espera un momento.", translation: "Wait a moment." },
    { id: 466, spanish: "vez", english: "time (occurrence)", example: "Una vez más.", translation: "One more time." },
    { id: 467, spanish: "forma", english: "way/form", example: "De esta forma.", translation: "This way." },
    { id: 468, spanish: "manera", english: "way/manner", example: "De ninguna manera.", translation: "No way." },
    { id: 469, spanish: "modo", english: "way/mode", example: "De todos modos.", translation: "Anyway." },
    { id: 470, spanish: "razón", english: "reason", example: "Tienes razón.", translation: "You're right." },
    { id: 471, spanish: "verdad", english: "truth", example: "Es la verdad.", translation: "It's the truth." },
    { id: 472, spanish: "problema", english: "problem", example: "No hay problema.", translation: "No problem." },
    { id: 473, spanish: "solución", english: "solution", example: "Encontré la solución.", translation: "I found the solution." },
    { id: 474, spanish: "pregunta", english: "question", example: "Tengo una pregunta.", translation: "I have a question." },
    { id: 475, spanish: "respuesta", english: "answer", example: "No sé la respuesta.", translation: "I don't know the answer." },
    { id: 476, spanish: "idea", english: "idea", example: "Buena idea.", translation: "Good idea." },
    { id: 477, spanish: "opinión", english: "opinion", example: "En mi opinión.", translation: "In my opinion." },
    { id: 478, spanish: "ejemplo", english: "example", example: "Por ejemplo.", translation: "For example." },
    { id: 479, spanish: "caso", english: "case", example: "En ese caso.", translation: "In that case." },
    { id: 480, spanish: "historia", english: "story/history", example: "Una historia interesante.", translation: "An interesting story." },
    { id: 481, spanish: "palabra", english: "word", example: "No entiendo esta palabra.", translation: "I don't understand this word." },
    { id: 482, spanish: "lengua", english: "language/tongue", example: "Mi lengua materna.", translation: "My mother tongue." },
    { id: 483, spanish: "idioma", english: "language", example: "Hablo tres idiomas.", translation: "I speak three languages." },
    { id: 484, spanish: "nombre", english: "name", example: "¿Cuál es tu nombre?", translation: "What's your name?" },
    { id: 485, spanish: "número", english: "number", example: "Dame tu número de teléfono.", translation: "Give me your phone number." },
    { id: 486, spanish: "edad", english: "age", example: "¿Cuál es tu edad?", translation: "What's your age?" },
    { id: 487, spanish: "fecha", english: "date", example: "¿Cuál es la fecha hoy?", translation: "What's the date today?" },
    { id: 488, spanish: "precio", english: "price", example: "¿Cuál es el precio?", translation: "What's the price?" },
    { id: 489, spanish: "valor", english: "value", example: "Tiene mucho valor.", translation: "It has a lot of value." },
    { id: 490, spanish: "guerra", english: "war", example: "La guerra terminó.", translation: "The war ended." },
    { id: 491, spanish: "paz", english: "peace", example: "Queremos la paz.", translation: "We want peace." },
    { id: 492, spanish: "amor", english: "love", example: "El amor es importante.", translation: "Love is important." },
    { id: 493, spanish: "vida", english: "life", example: "La vida es bella.", translation: "Life is beautiful." },
    { id: 494, spanish: "muerte", english: "death", example: "La muerte es parte de la vida.", translation: "Death is part of life." },
    { id: 495, spanish: "salud", english: "health", example: "La salud es lo primero.", translation: "Health comes first." },
    { id: 496, spanish: "enfermedad", english: "illness/disease", example: "Es una enfermedad común.", translation: "It's a common illness." },
    { id: 497, spanish: "mundo", english: "world", example: "Quiero viajar por el mundo.", translation: "I want to travel the world." },
    { id: 498, spanish: "naturaleza", english: "nature", example: "Me encanta la naturaleza.", translation: "I love nature." },
    { id: 499, spanish: "música", english: "music", example: "Escucho música todos los días.", translation: "I listen to music every day." },
    { id: 500, spanish: "arte", english: "art", example: "Me gusta el arte moderno.", translation: "I like modern art." }
];
